### ISSUE TITLE
Sentence-BERT

### ISSUE THREAD

**Issue by ogencoglu** [vector-ai/vectorhub#5]
Would be nice to have sentence-BERT embeddings as well:
https://arxiv.org/abs/1908.10084
https://www.sbert.net/

**Comment by danvass** [comment]
Thank you for the suggestion, we'll add it to the list of models we're looking to integrate!

If you're curious about creating a PR we've made some documentation about the process of adding new models here: https://vector-ai.github.io/vectorhub/how_to_add_a_model.html.

**Comment by JackyKoh** [comment]
Thanks for the great suggestion @ogencoglu . We have added sbert to master branch and will include it in the next version release as well. https://github.com/vector-ai/vectorhub/pull/6
