### ISSUE TITLE
Typo in https://hub.getvectorai.com/

### ISSUE THREAD

**Issue by borhan-kazimipour** [vector-ai/vectorhub#8]
The code example for Dense Passage Retrieval doesn't work as there an `s` is missing:
`from vectorhub.bi_encoder.text_text.torch_transformers import DPR2Vec` should be changed as `from vectorhub.bi_encoders.text_text.torch_transformers import DPR2Vec`

**Comment by JackyKoh** [comment]
Thanks for the issue @borhan-kazimipour. We've fixed the typo and should be updated in an upcoming version of https://hub.getvectorai.com
